// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCI02-R5TDUluiblH1tVb8sW6kOH7gnVlU',
//     appId: '1:844727730828:web:04241961a5d585aea9b1a9',
//     messagingSenderId: '844727730828',
//     projectId: 'appname-53946',
//     authDomain: 'appname-53946.firebaseapp.com',
//     storageBucket: 'appname-53946.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBwnKC7Mbmq6ilwJXrYLC957jQ18tlZbho',
//     appId: '1:844727730828:android:4f9042ad6f776cb2a9b1a9',
//     messagingSenderId: '844727730828',
//     projectId: 'appname-53946',
//     storageBucket: 'appname-53946.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD2Sg6uUK3TNdRPfx98aYGHUBBxdkEVAe0',
//     appId: '1:844727730828:ios:1b0b564b7a15f8c3a9b1a9',
//     messagingSenderId: '844727730828',
//     projectId: 'appname-53946',
//     storageBucket: 'appname-53946.firebasestorage.app',
//     iosBundleId: 'com.example.appname',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD2Sg6uUK3TNdRPfx98aYGHUBBxdkEVAe0',
//     appId: '1:844727730828:ios:1b0b564b7a15f8c3a9b1a9',
//     messagingSenderId: '844727730828',
//     projectId: 'appname-53946',
//     storageBucket: 'appname-53946.firebasestorage.app',
//     iosBundleId: 'com.example.appname',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCI02-R5TDUluiblH1tVb8sW6kOH7gnVlU',
//     appId: '1:844727730828:web:f791314759f0750fa9b1a9',
//     messagingSenderId: '844727730828',
//     projectId: 'appname-53946',
//     authDomain: 'appname-53946.firebaseapp.com',
//     storageBucket: 'appname-53946.firebasestorage.app',
//   );
// }
